# Generated by Django 5.2.17 on 2026-09-15 09:39

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def role_to_roles(apps, schema_editor):
    """Кожна наявна роль стає рядком у новій таблиці — нічого не губиться."""
    User = apps.get_model('accounts', 'User')
    UserRole = apps.get_model('accounts', 'UserRole')
    UserRole.objects.bulk_create(
        [UserRole(user_id=pk, role=role)
         for pk, role in User.objects.exclude(role='').values_list('pk', 'role')
         if role],
        ignore_conflicts=True,
    )


def roles_to_role(apps, schema_editor):
    """Назад — найповажніша з ролей людини, решта губиться (набір у поле не влізе)."""
    User = apps.get_model('accounts', 'User')
    UserRole = apps.get_model('accounts', 'UserRole')
    rank = ['super_admin', 'manager', 'teacher', 'student']
    best = {}
    for user_id, role in UserRole.objects.values_list('user_id', 'role'):
        if user_id not in best or rank.index(role) < rank.index(best[user_id]):
            best[user_id] = role
    for user_id, role in best.items():
        User.objects.filter(pk=user_id).update(role=role)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Супер-адмін'), ('manager', 'Менеджер'), ('teacher', 'Викладач'), ('student', 'Студент')], max_length=20, verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Роль користувача',
                'verbose_name_plural': 'Ролі користувачів',
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role')],
            },
        ),
        migrations.RunPython(role_to_roles, roles_to_role),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
