# Generated by Django 5.2.17 on 2026-09-12 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Початок')),
                ('end_time', models.TimeField(verbose_name='Кінець')),
                ('source', models.CharField(choices=[('academy', 'Академія'), ('teacher', 'Викладач')], max_length=10, verbose_name='Джерело')),
                ('notes', models.TextField(blank=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Створив(ла)')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Запис розкладу',
                'verbose_name_plural': 'Записи розкладу',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
