# Generated by Django 5.2.17 on 2026-09-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_scheduleentry_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва курсу')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['course__name', 'name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schedule.course', verbose_name='Курс'),
        ),
    ]
