# Generated by Django 5.2.17 on 2026-09-12 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_course_alter_subject_options_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='schedule.course', verbose_name='Курс'),
        ),
    ]
