# Generated by Django 5.2.17 on 2026-09-14 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_scheduleentry_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва групи')),
                ('start_date', models.DateField(verbose_name='Початок навчання')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Завершення навчання')),
                ('notes', models.TextField(blank=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='schedule.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule.group', verbose_name='Група'),
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Початок')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Завершення')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_subjects', to='schedule.group', verbose_name='Група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_subjects', to='schedule.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='group_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Предмет у групі',
                'verbose_name_plural': 'Предмети у групах',
                'ordering': ['group', 'start_date', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='group_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='schedule.groupsubject', verbose_name='Предмет у групі'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Початок')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Завершення')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schedule.group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Студент у групі',
                'verbose_name_plural': 'Студенти у групах',
                'ordering': ['group', 'student__last_name', 'student__first_name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'student', 'start_date'), name='unique_enrollment_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='groupsubject',
            constraint=models.UniqueConstraint(fields=('group', 'subject', 'start_date'), name='unique_group_subject_period'),
        ),
    ]
