# Generated by Django 5.2.17 on 2026-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_group_scheduleentry_group_groupsubject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['course__name', 'position', 'name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер у програмі'),
        ),
        migrations.AddField(
            model_name='subject',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок у програмі'),
        ),
    ]
